In [3]:
import torch
import numpy as np
import pandas as pd

dataset = "cifar100"
scenario = 'class_iid'
num_runs = 10
fpathheader = dataset + "_nfg5_ncls5_nproto20_run"
fpathpostfix = '_scenario_' + scenario + '_icarl_dual_b1ss_b2free_fixed_exp01'
avgacc = []

ntasks = 20
csvresult = np.zeros((num_runs, ntasks))
for r in range(num_runs):
    re = torch.load('logs/'+fpathheader + str(r)+fpathpostfix + '/acc_list_cumul.pth')
    csvresult[r,:] = re[:,1,:].squeeze()
    avg = np.mean(re[:,1,:].squeeze())
    print(avg)
    avgacc.append(avg)

result = sum(avgacc)/len(avgacc)
print('CVPR paper Table 2: ' + dataset+' : ' + str(result))
print(csvresult)

#write to csv files
test_df = pd.DataFrame(csvresult)
test_df.to_csv(('results/' + dataset +'_' + scenario +'_' + 'test.csv'), index=False, header=False)
print('saving results to ', ('results/' + dataset +'_' + scenario +'_' + 'test.csv') )


avgacc = []
csvresult = np.zeros((num_runs, ntasks))
for r in range(num_runs):
    re = torch.load('logs/'+fpathheader + str(r)+fpathpostfix + '/acc_list_ori.pth')
    csvresult[r,:] = re[:,1,:].squeeze()
    avg = np.mean(re[:,1,:].squeeze())
    print(avg)
    avgacc.append(avg)

result = sum(avgacc)/len(avgacc)
print('CVPR paper Table 2: ' + dataset+' : ' + str(result))
print(csvresult)

#write to csv files
test_df = pd.DataFrame(csvresult)
test_df.to_csv(('results/' + dataset +'_' + scenario +'_' + 'test_1st.csv'), index=False, header=False)
print('saving results to ', ('results/' + dataset +'_' + scenario +'_' + 'test_1st.csv') )

14.55877600778994
14.19448815670913
15.810559481196478
14.952144100481561
14.430895096217853
12.551900106558389
16.66859006520655
15.548944595909768
17.228263181864573
17.84903749810561
CVPR paper Table 2: cifar100 : 15.379359829003988
[[60.         36.7        24.06666667 19.6        17.8        13.96666667
  11.91428571 12.1        11.04444444  9.36        8.52727273  9.83333333
   8.56923077  7.07142857  7.45333333  7.1         7.36470588  5.48888889
   6.50526316  6.71      ]
 [59.         29.         20.4        17.1        18.92       14.13333333
  13.37142857 12.725      12.          9.96       10.16363636  7.36666667
   7.86153846  8.47142857  8.44        8.1125      7.02352941  6.13333333
   6.94736842  6.76      ]
 [77.         43.8        25.06666667 19.6        17.         15.66666667
  12.05714286 13.1        10.44444444 10.36       10.07272727  9.05
   8.15384615  6.8         6.01333333  7.275       6.55294118  5.7
   6.56842105  5.93      ]
 [60.         35.1        25.6

In [4]:
import torch
import numpy as np
import pandas as pd

dataset = "core50"
scenario = 'class_iid'
num_runs = 10
fpathheader = dataset + "_nfg2_ncls2_nproto20_run"
fpathpostfix = '_scenario_' + scenario + '_icarl_dual_b1ss_b2free_fixed_exp01'
avgacc = []

ntasks = 5
csvresult = np.zeros((num_runs, ntasks))
for r in range(num_runs):
    re = torch.load('logs/'+fpathheader + str(r)+fpathpostfix + '/acc_list_cumul.pth')
    csvresult[r,:] = re[:,1,:].squeeze()
    avg = np.mean(re[:,1,:].squeeze())
    print(avg)
    avgacc.append(avg)

result = sum(avgacc)/len(avgacc)
print('CVPR paper Table 2: ' + dataset+' : ' + str(result))
print(csvresult)

#write to csv files
test_df = pd.DataFrame(csvresult)
test_df.to_csv(('results/' + dataset +'_' + scenario +'_' + 'test.csv'), index=False, header=False)
print('saving results to ', ('results/' + dataset +'_' + scenario +'_' + 'test.csv') )


avgacc = []
csvresult = np.zeros((num_runs, ntasks))
for r in range(num_runs):
    re = torch.load('logs/'+fpathheader + str(r)+fpathpostfix + '/acc_list_ori.pth')
    csvresult[r,:] = re[:,1,:].squeeze()
    avg = np.mean(re[:,1,:].squeeze())
    print(avg)
    avgacc.append(avg)

result = sum(avgacc)/len(avgacc)
print('CVPR paper Table 2: ' + dataset+' : ' + str(result))
print(csvresult)

#write to csv files
test_df = pd.DataFrame(csvresult)
test_df.to_csv(('results/' + dataset +'_' + scenario +'_' + 'test_1st.csv'), index=False, header=False)
print('saving results to ', ('results/' + dataset +'_' + scenario +'_' + 'test_1st.csv') )

37.379999999999995
32.960740740740746
31.75925925925926
31.848888888888887
33.419259259259256
33.180740740740745
33.92074074074074
31.605185185185185
32.837037037037035
30.521481481481477
CVPR paper Table 2: core50 : 32.943333333333335
[[73.55555556 42.33333333 30.         23.27777778 17.73333333]
 [66.66666667 34.66666667 26.37037037 20.83333333 16.26666667]
 [61.55555556 37.22222222 26.07407407 16.38888889 17.55555556]
 [64.         36.44444444 25.33333333 18.22222222 15.24444444]
 [70.44444444 37.44444444 25.85185185 18.33333333 15.02222222]
 [66.66666667 33.55555556 30.14814815 18.77777778 16.75555556]
 [70.22222222 36.         26.37037037 21.05555556 15.95555556]
 [68.44444444 33.77777778 23.7037037  17.61111111 14.48888889]
 [68.44444444 33.55555556 28.07407407 19.66666667 14.44444444]
 [69.77777778 37.66666667 17.62962963 15.44444444 12.08888889]]
saving results to  results/core50_class_iid_test.csv
56.97777777777778
50.8
52.0
39.68888888888888
46.39999999999999
45.7777777777777